name = "Scallopverse"
uuid = "e45babb8-668d-4146-b1e2-35262bdb39f6"
authors = ["Grisha Szep <grisha.szep@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
